apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - image: nginx
        name: my-webserver
      - image: nginx
        name: nginx
        env:
          - name: api-url
            value: dev.ifcloud.com.br
        resources:
          requests:
            cpu: 2000m
            memory: 1Gi

