apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    labels:
      app: hello-world
    spec:
      containers:
      - image: monopole/hello:1
        name: hello-world
        ports:
          - containerPort: 8080


