kind: Service
apiVersion: v1
metadata:
  name: service-hello-world
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8666
    targetPort: 8080